import { Challenge } from './types';

export const mockChallenges: Challenge[] = [
  {
    id: 'show-up',
    title: 'Show Up Challenge',
    description: 'Check in daily to build your streak and earn BCP. Consistency is key!',
    type: 'daily-checkin',
    thumbnail: '🔥',
    participants: 1247,
    bcpReward: 1,
    duration: 'Ongoing',
    isActive: true,
    entryFee: 0.3,
  },
  {
    id: 'streak-30',
    title: '30-Day Streak Master',
    description: 'Maintain a 30-day check-in streak without missing a single day. Complete the challenge to win the pot!',
    type: 'streak-milestone',
    thumbnail: '🎯',
    participants: 523,
    bcpReward: 5,
    duration: '30 Days',
    isActive: true,
    entryFee: 0.3,
  },
  {
    id: 'community-vote-jan',
    title: 'January Community Choice',
    description: 'Vote on the next challenge theme. Most active voters earn bonus BCP!',
    type: 'community-vote',
    thumbnail: '🗳️',
    participants: 892,
    bcpReward: 2,
    duration: '7 Days',
    startDate: '2026-01-30',
    endDate: '2026-02-06',
    isActive: true,
    entryFee: 0,
  },
  {
    id: 'trivia-master',
    title: 'Base Trivia Master',
    description: 'Answer daily trivia questions about Base blockchain. Top scorers win big!',
    type: 'skill-based',
    thumbnail: '🧠',
    participants: 1876,
    bcpReward: 3,
    duration: '14 Days',
    startDate: '2026-01-28',
    endDate: '2026-02-11',
    isActive: true,
    entryFee: 0.3,
  },
];
